# Generated by Django 5.2.15 on 2026-07-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0003_whatsappconversationsession_awaiting_language_reselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='language_picker_pending_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
