# Generated by Django 5.x

from django.db import migrations, models


def mark_existing_sessions_onboarded(apps, schema_editor):
    Session = apps.get_model("qualification", "WhatsAppConversationSession")
    Session.objects.filter(language__isnull=False).update(onboarding_intro_sent=True)
    Session.objects.filter(last_message_at__isnull=False).update(onboarding_intro_sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ("qualification", "0009_whatsappconversationsession_booking_link_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconversationsession",
            name="onboarding_intro_sent",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.RunPython(mark_existing_sessions_onboarded, migrations.RunPython.noop),
    ]
