# Generated by Django 5.2.17 on 2026-08-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0016_whatsappconversationsession_accepted_fields_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='business_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='customer_type',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='launch_timeline',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='main_goal',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='paid_ads',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='preferred_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='qualification_complete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='qualification_step',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='referral_source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='website_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversationsession',
            name='whatsapp_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
